name: Create master promotion pull request
on:
  push:
    branches:
      - 'releases/**'
jobs:
  masterPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ github.ref }}
          base: main