name: Reusable stage deploy workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        echo "VERSION=`echo ${{ env.inputs.stages }} | sed -n s\~/-/g -e s/^v//`" >> "$GITHUB_ENV"
        run: echo  The tags are ${{ inputs.stage }} - ${{ inputs.version }}