name: Reusable stage deploy workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: |
          echo "VERSION=`echo ${{ inputs.version }} | sed s/~/-/g | sed s/v//g`" >> "$GITHUB_ENV"
          echo  The tags are ${{ inputs.stage }} - ${{ inputs.version }}