name: Stage deploy

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      stage:
        description: 'Stage'
        required: true
        type: choice
        options:
          - gcdn_gc_preprod_edges_stage1
          - gcdn_gc_preprod_edges_stage2
          - gcdn_gc_preprod_edges_stage99
          - gcdn_gc_prod_edges_stage1
          - gcdn_gc_prod_edges_stage2
          - gcdn_gc_prod_edges_stage3
          - gcdn_gc_prod_edges_stage4
          - gcdn_gc_prod_edges_stage5
          - gcdn_gc_prod_edges_stage99

jobs:
  build_deb:
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.stage }} - ${{ inputs.version }}

  call-deploy-workflow:
    needs: build_deb
    env:
      VERSION: ${{ needs.build_deb.outputs.version }}
    uses: ./.github/workflows/deploy.yaml
    with:
      version: ${{ github.ref_name }}
      stage: ${{ inputs.stage }}
