name: Build Release

on:
  release:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo new release