name: Create Release Tag

permissions:
  contents: write

on:
  pull_request:
    types:
      - closed
    branches:
      - 'releases/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo release
        run: |
          cargo install cargo-release
          cargo release tag --execute